title: Dodenherdenking TU Delft
email: ksiemonsma@tudelft.nl
description: >- # this means to ignore newlines until "baseurl:"
  This website is dedicated to the people who have given their live in the name of freedom during the Second World War.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Preferred IIIF viewer
# viewer_base_url: http://uv-v4.netlify.app/uv.html#?manifest=
# viewer_base_url: https://projectmirador.org/embed/?manifest= 
viewer_base_url: http://universalviewer.io/uv.html?manifest=

# IIIF Server settings
image_base_url: https://dlc.services/iiif-img/7/
manifest_base_url: https://dlc.services/iiif-resource/delft/string1/

collections:
  people:
    output: true
